# Generated by Django 5.0.7 on 2024-12-11 22:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese un nombre', max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(help_text='Ingrese un nombre', max_length=50, unique=True, verbose_name='Nombre')),
                ('dni', models.CharField(help_text='Ingrese un número de cedula', max_length=13, unique=True, verbose_name='Número de cedula')),
                ('mobile', models.CharField(help_text='Ingrese un número de teléfono', max_length=10, unique=True, verbose_name='Teléfono celular')),
                ('address', models.CharField(blank=True, help_text='Ingrese una dirección', max_length=500, null=True, verbose_name='Dirección')),
                ('email', models.CharField(help_text='Ingrese un correo electrónico', max_length=50, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese un nombre', max_length=50, verbose_name='Nombre')),
                ('ruc', models.CharField(help_text='Ingrese el ruc de la empresa', max_length=13, verbose_name='Ruc')),
                ('address', models.CharField(help_text='Ingrese una dirección', max_length=200, verbose_name='Dirección')),
                ('mobile', models.CharField(help_text='Ingrese un número de teléfono celular', max_length=10, verbose_name='Teléfono celular')),
                ('phone', models.CharField(help_text='Ingrese un número de teléfono convencional', max_length=9, verbose_name='Teléfono convencional')),
                ('email', models.CharField(help_text='Ingrese un correo electrónico', max_length=50, verbose_name='Email')),
                ('website', models.CharField(help_text='Ingrese una página web', max_length=250, verbose_name='Página web')),
                ('description', models.CharField(blank=True, help_text='Ingrese una descripción', max_length=500, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Logotipo de la empresa')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'permissions': (('change_company', 'Can change Empresa'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(help_text='Ingrese un nombre', max_length=50, unique=True, verbose_name='Nombre')),
                ('dni', models.CharField(help_text='Ingrese un número de cedula', max_length=13, unique=True, verbose_name='Número de cedula')),
                ('mobile', models.CharField(help_text='Ingrese un número de teléfono', max_length=10, unique=True, verbose_name='Teléfono celular')),
                ('address', models.CharField(blank=True, help_text='Ingrese una dirección', max_length=500, null=True, verbose_name='Dirección')),
                ('email', models.CharField(help_text='Ingrese un correo electrónico', max_length=50, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='HarvestControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('total_bunches', models.IntegerField(default=0, verbose_name='Total de racimos cosechados')),
                ('total_boxes', models.IntegerField(default=0, verbose_name='Total de cajas')),
                ('observations', models.CharField(blank=True, help_text='Ingrese una descripción', max_length=5000, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Control de Cosecha',
                'verbose_name_plural': 'Controles de Cosecha',
                'permissions': (('view_harvest_control', 'Can view Control de Cosecha'), ('add_harvest_control', 'Can add Control de Cosecha'), ('delete_harvest_control', 'Can delete Control de Cosecha')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ingrese un código', max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Ingrese un nombre', max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ingrese un código', max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Ingrese un nombre', max_length=100, unique=True, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio')),
                ('category', models.CharField(choices=[('banana', 'Banano'), ('plantain', 'Platano')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, help_text='Ingrese una descripción', max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Planta',
                'verbose_name_plural': 'Tipo de Plantas',
                'permissions': (('view_plant_type', 'Can view Tipo de Planta'), ('add_plant_type', 'Can add Tipo de Planta'), ('change_plant_type', 'Can change Tipo de Planta'), ('delete_plant_type', 'Can delete Tipo de Planta')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese un nombre', max_length=50, unique=True, verbose_name='Nombre')),
                ('ruc', models.CharField(help_text='Ingrese un número de ruc', max_length=13, unique=True, verbose_name='Ruc')),
                ('mobile', models.CharField(help_text='Ingrese un número de teléfono', max_length=10, unique=True, verbose_name='Teléfono celular')),
                ('address', models.CharField(blank=True, help_text='Ingrese una dirección', max_length=500, null=True, verbose_name='Dirección')),
                ('email', models.CharField(help_text='Ingrese un correo electrónico', max_length=50, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese un nombre', max_length=150, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Ingrese un código', max_length=20, unique=True, verbose_name='Código')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resource/%Y/%m/%d', verbose_name='Imagen')),
                ('is_equipment', models.BooleanField(default=False, verbose_name='¿Es un equipo?')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese un nombre', max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Recurso',
                'verbose_name_plural': 'Tipos de Insumos',
                'permissions': (('view_resource_type', 'Can view Tipo de Recurso'), ('add_resource_type', 'Can add Tipo de Recurso'), ('change_resource_type', 'Can change Tipo de Recurso'), ('delete_resource_type', 'Can delete Tipo de Recurso')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Ingrese un color', max_length=50, verbose_name='Color de la cinta')),
                ('name', models.CharField(help_text='Ingrese un nombre', max_length=500, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, help_text='Ingrese una descripción', max_length=500, null=True, verbose_name='Descripción')),
                ('week', models.PositiveIntegerField(default=0, unique=True, verbose_name='Semana')),
            ],
            options={
                'verbose_name': 'Cinta',
                'verbose_name_plural': 'Cintas',
                'ordering': ['week'],
            },
        ),
        migrations.CreateModel(
            name='TypeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese un nombre', max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gastos',
                'permissions': (('view_type_expense', 'Can view Tipo de Gasto'), ('add_type_expense', 'Can add Tipo de Gasto'), ('change_type_expense', 'Can change Tipo de Gasto'), ('delete_type_expense', 'Can delete Tipo de Gasto')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Salario')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='HarvestControlDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('boxes', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('harvest_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.harvestcontrol')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.planttype')),
            ],
            options={
                'verbose_name': 'Detalle de Control de Cosecha',
                'verbose_name_plural': 'Detalles de Control de Cosecha',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total de IVA')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total a pagar')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.client', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.company', verbose_name='Compañia')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'permissions': (('view_invoice', 'Can view Factura'), ('add_invoice', 'Can add Factura'), ('delete_invoice', 'Can delete Factura'), ('print_invoice', 'Can print Factura')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.invoice')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.planttype')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalle de Facturas',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InvoiceHarvestControlDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('harvest_control_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.harvestcontroldetail')),
                ('invoice_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.invoicedetail')),
            ],
            options={
                'verbose_name': 'Detalle de Control de Cosecha Factura',
                'verbose_name_plural': 'Detalle de Control de Cosecha Facturas',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ingrese un código', max_length=20, unique=True, verbose_name='Código')),
                ('latitude', models.CharField(help_text='Ingrese una latitud', max_length=30, verbose_name='Latitud')),
                ('longitude', models.CharField(help_text='Ingrese una longitud', max_length=30, verbose_name='Longitud')),
                ('status', models.CharField(choices=[('seedling', 'Plántula'), ('planted', 'Plantada')], default='seedling', max_length=10, verbose_name='Estado')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.lot', verbose_name='Lote')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.planttype', verbose_name='Tipo de Planta')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=True)),
                ('lots', models.ManyToManyField(to='pos.lot')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'permissions': (('view_production', 'Can view Producción'), ('add_production', 'Can add Producción'), ('delete_production', 'Can delete Producción')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='harvestcontrol',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.production', verbose_name='Producción'),
        ),
        migrations.CreateModel(
            name='ProductionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.contract')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.production')),
            ],
            options={
                'verbose_name': 'Contracto de la Producción',
                'verbose_name_plural': 'Contractos de la Producción',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductionPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.plant')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.production')),
            ],
            options={
                'verbose_name': 'Planta de la Producción',
                'verbose_name_plural': 'Plantas de la Producción',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Ingrese un número de factura', max_length=8, unique=True, verbose_name='Número de factura')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total de IVA')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total a pagar')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'permissions': (('view_purchase', 'Can view Compra'), ('add_purchase', 'Can add Compra'), ('delete_purchase', 'Can delete Compra')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('guarantee', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('active', models.BooleanField(default=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.purchase')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.resource')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.inventory')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.production')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.resource')),
            ],
            options={
                'verbose_name': 'Recurso de la Producción',
                'verbose_name_plural': 'Recursos de la Producción',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.resourcetype', verbose_name='Tipo de recurso'),
        ),
        migrations.CreateModel(
            name='TapeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('observations', models.CharField(blank=True, max_length=500, null=True, verbose_name='Detalles')),
                ('production_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.productionplant')),
                ('tape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.tape')),
            ],
            options={
                'verbose_name': 'Asignación de cintas por semana',
                'verbose_name_plural': 'Asignaciones de cintas por semana',
                'permissions': (('view_tape_assignment', 'Can view Asignación de cintas por semana'), ('add_tape_assignment', 'Can add Asignación de cintas por semana'), ('delete_tape_assignment', 'Can delete Asignación de cintas por semana')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='harvestcontroldetail',
            name='tape_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.tapeassignment'),
        ),
        migrations.CreateModel(
            name='ActivityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('observations', models.CharField(blank=True, help_text='Ingrese una descripción', max_length=5000, null=True, verbose_name='Observaciones')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.activity', verbose_name='Actividad')),
                ('tape_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.tapeassignment', verbose_name='Asignación de cintas por semana')),
            ],
            options={
                'verbose_name': 'Control de Actividades Agronómicas',
                'verbose_name_plural': 'Controles de Actividades Agronómicas',
                'ordering': ['-date_joined'],
                'permissions': (('view_activity_control', 'Can view Control de Actividades Agronómicas'), ('add_activity_control', 'Can add Control de Actividades Agronómicas'), ('delete_activity_control', 'Can delete Control de Actividades Agronómicas')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TapedFruitControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('quantity', models.IntegerField(default=0, verbose_name='Número de racimos en la planta')),
                ('observations', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Observaciones')),
                ('tape_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.tapeassignment', verbose_name='Asignación de cintas por semana')),
            ],
            options={
                'verbose_name': 'Control de Fruta Encintada',
                'verbose_name_plural': 'Controles de Fruta Encintada',
                'ordering': ['-date_joined'],
                'permissions': (('view_taped_fruit_control', 'Can view Control de Fruta Encintada'), ('add_taped_fruit_control', 'Can add Control de Fruta Encintada'), ('delete_taped_fruit_control', 'Can delete Control de Fruta Encintada')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Ingrese los detalles (opcional)', max_length=500, null=True, verbose_name='Detalles')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor')),
                ('type_expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.typeexpense', verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
